#---------------------------------#
#       Hyper Parameters        
#---------------------------------#
K_NEIGHBOR: 2
SINKHORN_ITERS: 8
BT_DIST_MASK: False
DIST_THRESH: 300

# Options : vanilla, FixedEdgeDim , ProgressiveEdgeDim , RawEdgeAttr
Edge_mode: 'vanilla'
# Options : vanilla , graphConv , doubleEdgeEmb , selfConcat , StaticSelfConcat , SwapConv
GraphModel_type: 'vanilla'

#---------------------------------#
#         Model Structure
#      1. Node_Encoder
#      2. Edge_Encoder
#      3. Static_Graph_Model
#      4. Dynamic_Graph_Model
#      5. Fuse_Model
#---------------------------------#

#---------------------------------#
node_encoder:
  backbone: 'densenet121'
  wight_path: null
  dims_list: [1024,512,256,128,64,32]
  layer_type: 'linear'
  layer_bias: False
  use_batchnorm: True
  activate_func: 'relu'
  lrelu_slope: 0.0


#---------------------------------#
edge_encoder:
  #---------------------------------#
  #  Options : 
  #            ImgNorm4 | SrcNorm4          | TgtNorm4             | MeanSizeNorm4  | MeanHeightNorm4 
  #      MeanWidthNorm4 | CorverxNorm4      | MaxNorm4             | IOUd5          | IOU5
  #      GIOUd5         |  GIOU5            | DIOUd5               | DIOU5          | DIOU-Cos6 
  #      IouFamily8-vanilla       |   IouFamily8-convex       |    IouFamily8-separate      
  #      IouFamily8-vanilla-seq   |   IouFamily8-convex-seq   |    IouFamily8-separate-seq
  #      ConvexNorm4-v2 |   MaxNorm4-v2     | GIOUd5-v2            | GIOU5-v2       | DIOU5-v2
  #           CIOU5-v2  |   IouFamily6-convex
  #---------------------------------#
  edge_type: 'ConvexNorm4-v2'
  dims_list: [4,16,16]
  layer_type: 'linear'
  layer_bias: False
  use_batchnorm: True
  activate_func: 'relu'
  lrelu_slope: 0.0
  # static graph construction settings
  bt_cosine: False 
  bt_self_loop: True
  bt_directed: True


#---------------------------------#
# Attention about following variables `msgLayer_dims` , `updLayer_dims` and `fuseLayer_dims`:
#   1. support List type or tuple type 
#   2. first item means input dimension
#   3. last item means output dimension
#   4. the middle items means the hidden dimension no matter how many numbers of items 
#   
#   5. if set [] , there is no relavant layers built.
#      careful to set None
#
#   6. When there are two items in the variables,
#      the first item still means input, and the last one still means output
#
#   7. When there are only one items in the variables,
#      the only item become the input dimension 
#      and the output dimension is the same as the input dimension
#---------------------------------#





#---------------------------------#
#   3. Static_Graph_Model
# There are three GCN , and the dimension of each layer
# is defined in the following list.
#---------------------------------#
static_graph_model:
  nodeEmb_size: [32,64,96]
  edgeEmb_size: [16,16,16]
  msgLayer_dims:
    - [48,64,64]
    - [80,96,96]
    - [112,128,128]
  updLayer_dims:
    - [64,64]
    - [96,96]
    - [128,128]
  aggr: 'max'
  layer_type: 'linear'
  layer_bias: False
  use_batchnorm: True
  activate_func: 'lrelu'
  lrelu_slope: 0.1

#---------------------------------#
#   4. Dynamic_Graph_Model
# There are three GCN , and the dimension of each layer
# is defined in the following list.
#---------------------------------#
dynamic_graph_model:
  nodeEmb_size: [64,96]
  edgeEmb_size: [16,16]
  msgLayer_dims:
    - [128,96,96]
    - [192,128,128]
  updLayer_dims:
    - []
    - []
    - []
  aggr: 'max'
  # module layer settings 
  layer_type: 'linear'
  layer_bias: False
  use_batchnorm: True
  activate_func: 'lrelu'
  lrelu_slope: 0.1
  # dynamic graph construction settings
  bt_cosine: False 
  bt_self_loop: True
  bt_directed: True

#---------------------------------#
fuse_model:
  # [in_dim , mid_dim, out_dim]
  fuseLayer_dims: 
    - [512,1024]
    - [1536,768,384,192] 
  layer_type: 'Conv1d'
  layer_bias: False
  use_batchnorm: True
  activate_func: 'lrelu'
  lrelu_slope: 0.2