#---------------------------------#
# Configuration for dataset paths, data preprocessing, and data split
# - DETECTOR             : Object detector to use for detection tasks. Can be 'FRCNN', 'DPM', etc.
# - DATA_DIR             : Path to the directory where training data is stored.
# - ACCEPTABLE_OBJ_TYPE  : List of acceptable object types (e.g., person, car, etc.).
# - MOT17_TRAIN_NAME     : Names of the training sequences in the MOT17 dataset.
# - MOT17_TRAIN_START    : Start frame for each training sequence.
# - MOT17_VAL_NAME       : Names of the validation sequences in the MOT17 dataset.
# - MOT17_VAL_START      : Start frame for each validation sequence.
# - MOT17ALLFRAMENUM     : Total number of frames in each MOT17 sequence.
# - MOT17ALLFRAMENUM     : Total number of frames in each MOT17 sequence.
# - TRACKBACK_WINDOW     : Number of previous frames to use for constructing Tracklet Graph.
#---------------------------------#


DETECTOR: 'FRCNN'  
DATA_DIR: 'datasets/MOT17/train'  
ACCEPTABLE_OBJ_TYPE: [1, 2, 7]  
MOT17_TRAIN_NAME: 
  - 'MOT17-02'
  - 'MOT17-04'
  - 'MOT17-05'
  - 'MOT17-09'
  - 'MOT17-10'
  - 'MOT17-11'
  - 'MOT17-13'  
MOT17_TRAIN_START: 
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2  
MOT17_VAL_NAME: 
  - 'MOT17-02'
  - 'MOT17-04'
  - 'MOT17-05'
  - 'MOT17-09'
  - 'MOT17-10'
  - 'MOT17-11'
  - 'MOT17-13'   
MOT17_VAL_START: 
  - 501
  - 951
  - 738
  - 426
  - 555
  - 801
  - 651  
MOT17ALLFRAMENUM:
  MOT17-01: 450
  MOT17-02: 600
  MOT17-03: 1500
  MOT17-04: 1050
  MOT17-05: 837
  MOT17-06: 1194
  MOT17-07: 500
  MOT17-08: 625
  MOT17-09: 525
  MOT17-10: 654
  MOT17-11: 900
  MOT17-12: 900
  MOT17-13: 750
  MOT17-14: 750  
TRACKBACK_WINDOW: 10  
MAXAGE: 100  # Maximum age for tracking an object.
