graph_model_params:
  reid_module:
    arch: fastreid_market_bot_R50-ibn

  node_encoder_feats_dict:
    node_in_dim: 2048
    node_fc_dims: [512,128]
    node_out_dim: 32
    dropout_p: 0
    use_batchnorm: False

  edge_encoder_feats_dict:
    edge_in_dim: 6
    edge_fc_dims: [18, 18]
    edge_out_dim: 16
    dropout_p: 0
    use_batchnorm: False

  # In size is 2 * encoded nodes + 1 * encoded edges
  static_graph_feats_dict:
    fc_dims: [56, 32]
    dropout_p: 0
    use_batchnorm: False

  classifier_feats_dict:
    edge_in_dim: 16
    edge_fc_dims: [8]
    edge_out_dim: 1
    dropout_p: 0
    use_batchnorm: False

  cnn_params:
    arch: resnet50
    model_weights_path:
      resnet50: trained_models/reid/resnet50_market_cuhk_duke.tar-232

  trajectory_encoder_params:
    input_dim: 0
    fc_dim: 64
    out_dim: 32