RESIZE_TO_CNN: [256, 128]
FUSION_METHOD: EMAFF
EMA_LAMBDA: 0.9
MIN_DET_CONF: 0.1
DET_CONF_GATE: 0.5
FIRST_MATCH_THRESH: 0.05  # DEFAULT: 0.05
SECOND_MATCH_LAMBDA: 0.5
SECOND_MATCH_THRESH: 0.5
THIRD_MATCH_THRESH: 0.1
DET2TRA_CONF: 0.7
CNT_TO_ACTIVE: 1
CNT_TO_SLEEP: 1
MAX_CNT_TO_DEAD: 30  # Maximum age for tracking an object
FEATURE_LIST_SIZE: 10