#---------------------------------#
# Base configuration for experiment settings and training parameters
# - RANDOM_SEED    : Random seed for reproducibility. Set to a fixed value for deterministic results.
# - LOG_PERIOD     : Period (in iterations) for logging training progress.
# - CHECKPOINT_PERIOD  : Period (in epochs) to save model checkpoints.
# - WORK_DIR       : Directory to save logs, checkpoints, and results.
# - DEVICE         : Device to run the model. 'cuda' for GPU, 'cpu' for CPU.
# - GPU_IDS        : List of GPU IDs to use. If not specified, all available GPUs will be used.
# - NUM_WORKS      : Number of workers for data loading. Higher values can speed up data loading.
# 
# - LR             : Initial learning rate for training.
# - WEIGHT_DECAY   : Weight decay (L2 regularization) to prevent overfitting.
# - MIN_LR_RATIO   : Minimum learning rate ratio for learning rate scheduler.
# - BATCH_SIZE     : Batch size for training.
# - MAXEPOCH       : Total number of training epochs.
# - WARMUP_EPOCHS  : Number of warm-up epochs at the start of training with a lower learning rate.
# - NO_AUG_EPOCHS  : Number of epochs to disable data augmentation (if any).
# - SCHEDULER      : Learning rate scheduler. Options: 'cos', 'warmcos', 'yoloxwarmcos','yoloxsemiwarmcos'
# - WARM_LR        : Warm-up learning rate (used in warm-up phase).
#---------------------------------#
RANDOM_SEED: 1  
LOG_PERIOD: 50        
CHECKPOINT_PERIOD: 5  
WORK_DIR: "experiments"  
DEVICE: 'cuda'  
GPU_IDS: [0, 1] 
NUM_WORKS: 4
EMABLE_AMP: True

LR: 1.25e-4   
WEIGHT_DECAY: 0.00001   
MIN_LR_RATIO: 0.05   
BATCH_SIZE: 16   
MAXEPOCH: 50  
WARMUP_EPOCHS: 5   
NO_AUG_EPOCHS: 0  
SCHEDULER: 'yoloxwarmcos'  
WARM_LR: 0  
